### ISSUE TITLE
Error : lack of description

### ISSUE THREAD

**Issue by minanagehsalalma** [PerezMascato/URLCADIZ#2]
Pls add more to the readme

**Comment by PerezMascato** [comment]
What do you plan to add?

**Comment by minanagehsalalma** [comment]
> What do you plan to add?

@PerezMascato you not me... 

A bit of what the script is capable of  and its purpose and sure the list of features that it provides.

**Comment by djhashh** [comment]
+1 Same. Let's have some documentation

**Comment by Bubblebug17** [comment]
Yes, some usage examples would be great!!

**Comment by minanagehsalalma** [comment]
And some screen shots and maybe a video for sure.

**Comment by PerezMascato** [comment]
https://youtu.be/LwVc4-JkdfA

**Comment by minanagehsalalma** [comment]
> https://youtu.be/LwVc4-JkdfA

@PerezMascato lol so it's redirect using shortened links ......  does this even work on chrome or what happens to the link when you post it in messager or similar apps with link preview.

**Comment by PerezMascato** [comment]
@minanagehsalalma Yes
