### ISSUE TITLE
Grate, but not working in some cases.

### ISSUE THREAD

**Issue by jaykali** [PerezMascato/URLCADIZ#7]
This is not working with ngrok URLs. Like we have a URL http://7711dd0d.ngrok.io but this tool is not able to give results it shows error. What to do?

**Comment by PerezMascato** [comment]
Hello!

In a very short time it is solved, comes URLCADIZ v.2

**Comment by PerezMascato** [comment]
URLCADIZ v.2 available

**Comment by Tanvir-Rezwan** [comment]
I tried today but its still error
