### ISSUE TITLE
Multiple Issues - v1

### ISSUE THREAD

**Issue by protonc0der19** [PerezMascato/URLCADIZ#8]
1.- Why do u add "#SYSCALL" at the end?? lmao..

2.- OOP Must be added in case Multiple functions of same methodology are being used.

3.- File "requeriments.txt" is not actually "requeriments.txt" IT IS: "requirements.txt"

4.- Please: Do not mix two languages in same program, or Spanish or English (I'd recommend you EN) but DO NOT mix them.

5.- You DO NOT need to cast input's as string types as they are already a string.

6.- The 90% of your code is redundant... you can make it a lot smaller as you are repeating a lot of unnecessary code.

Proof:
```
def EnlaceGoogle():
    os.system('clear')
    print("You have selected Google.")
    OriginalLink = str(input("\nOriginal URL: "))
    
    print("\nInput something that: new-user-in-twitter-this-is-a-perez-mascato-i-love")
    Postlink = str(input("\nPost LINK: "))
    os.system('clear')
    Shortener = pyshorteners.Shortener()
    EndLink = Shortener.tinyurl.short(OriginalLink)
    Withouthttp = EndLink[7:]
    print(f"\033[95m\nYour link is: https://www.google.com-{Postlink}@{Withouthttp}")
    Other()

def EnlaceYoutube():
    os.system('clear')
    print("You have selected Youtube.")
    OriginalLink = str(input("\nOriginal URL: "))
    
    print("\nInput something that: new-video-in-youtube-this-is-a-perez-mascato-i-love")
    Postlink = str(input("\nPost LINK: "))

    Shortener = pyshorteners.Shortener()
    EndLink = Shortener.tinyurl.short(OriginalLink)
    Withouthttp = EndLink[7:]
    os.system('clear')
    print(f"\033[95m\nYour link is: https://www.youtube.com-video-{Postlink}@{Withouthttp}")
    
    Other()
```

Why not just an array with the link getting changed?

7.- This is more a recommendation than an issue. I recommend you to, instead of calling Main() directly use the following wrapper:

```
if __name__ == '__main__':
    Main()
```
8.- Another recommendation: You are using a wrong notation, as described in the Oficial Python Documentation:
`Function names should be lowercase, with words separated by underscores as necessary to improve readability.`

Source: https://www.python.org/dev/peps/pep-0008/

9.- Another recomendation for the Python3 version, is to use parentheses when using conditionals, you are not using them.

10.- This is more an error than a recommendation... WTF:

```
import time
import pyshorteners
from time import sleep
```

Why are u importing the whole time library and then importing one of It's functions once it is already loaded???

**Comment by PerezMascato** [comment]
Hello protonc0der, 
thnx for you contribution, I'll create soon a URLCADIZ v.2,

I'll add your contribution
